/*
 Highcharts JS v8.2.2 (2021-01-18)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(z){d(z);d.Highcharts=z;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function z(d,b,h,f){d.hasOwnProperty(b)||(d[b]=f.apply(null,h))}d=d?d._modules:{};z(d,"Extensions/Pane.js",[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Pointer.js"],d["Core/Utilities.js"],
d["Mixins/CenteredSeries.js"]],function(d,b,h,f,a,v){function e(c,a,k){return Math.sqrt(Math.pow(c-k[0],2)+Math.pow(a-k[1],2))<=k[2]/2}var q=a.addEvent,n=a.extend,w=a.merge,c=a.pick,k=a.splat;d.prototype.collectionsWithUpdate.push("pane");a=function(){function c(c,a){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:h.neutralColor20,
backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,h.backgroundColor],[1,h.neutralColor10]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(c,a)}c.prototype.init=function(c,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(c)};c.prototype.setOptions=function(c){this.options=w(this.defaultOptions,this.chart.angular?{background:{}}:void 0,c)};c.prototype.render=function(){var c=this.options,a=this.options.background,l=this.chart.renderer;
this.group||(this.group=l.g("pane-group").attr({zIndex:c.zIndex||0}).add());this.updateCenter();if(a)for(a=k(a),c=Math.max(a.length,this.background.length||0),l=0;l<c;l++)a[l]&&this.axis?this.renderBackground(w(this.defaultBackgroundOptions,a[l]),l):this.background[l]&&(this.background[l]=this.background[l].destroy(),this.background.splice(l,1))};c.prototype.renderBackground=function(c,a){var k="animate",l={"class":"highcharts-pane "+(c.className||"")};this.chart.styledMode||n(l,{fill:c.backgroundColor,
stroke:c.borderColor,"stroke-width":c.borderWidth});this.background[a]||(this.background[a]=this.chart.renderer.path().add(this.group),k="attr");this.background[a][k]({d:this.axis.getPlotBandPath(c.from,c.to,c)}).attr(l)};c.prototype.updateCenter=function(c){this.center=(c||this.axis||{}).center=v.getCenter.call(this)};c.prototype.update=function(c,a){w(!0,this.options,c);w(!0,this.chart.options.pane,c);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(c){c.pane===this&&
(c.pane=null,c.update({},a))},this)};return c}();d.prototype.getHoverPane=function(c){var a=this,k;c&&a.pane.forEach(function(l){var b=c.chartX-a.plotLeft,f=c.chartY-a.plotTop;e(a.inverted?f:b,a.inverted?b:f,l.center)&&(k=l)});return k};q(d,"afterIsInsidePlot",function(c){this.polar&&(c.isInsidePlot=this.pane.some(function(a){return e(c.x,c.y,a.center)}))});q(f,"beforeGetHoverData",function(a){var k=this.chart;k.polar?(k.hoverPane=k.getHoverPane(a),a.filter=function(l){return l.visible&&!(!a.shared&&
l.directTouch)&&c(l.options.enableMouseTracking,!0)&&(!k.hoverPane||l.xAxis.pane===k.hoverPane)}):k.hoverPane=void 0});q(f,"afterGetHoverData",function(c){var a=this.chart;c.hoverPoint&&c.hoverPoint.plotX&&c.hoverPoint.plotY&&a.hoverPane&&!e(c.hoverPoint.plotX,c.hoverPoint.plotY,a.hoverPane.center)&&(c.hoverPoint=void 0)});b.Pane=a;return b.Pane});z(d,"Core/Axis/HiddenAxis.js",[],function(){return function(){function d(){}d.init=function(b){b.getOffset=function(){};b.redraw=function(){this.isDirty=
!1};b.render=function(){this.isDirty=!1};b.createLabelCollector=function(){return function(){}};b.setScale=function(){};b.setCategories=function(){};b.setTitle=function(){};b.isHidden=!0};return d}()});z(d,"Core/Axis/RadialAxis.js",[d["Core/Axis/Axis.js"],d["Core/Axis/Tick.js"],d["Core/Axis/HiddenAxis.js"],d["Core/Utilities.js"]],function(d,b,h,f){var a=f.addEvent,v=f.correctFloat,e=f.defined,q=f.extend,n=f.fireEvent,w=f.merge,c=f.pick,k=f.relativeLength,l=f.wrap;f=function(){function b(){}b.init=
function(a){var l=d.prototype;a.setOptions=function(c){c=this.options=w(a.constructor.defaultOptions,this.defaultPolarOptions,c);c.plotBands||(c.plotBands=[]);n(this,"afterSetOptions")};a.getOffset=function(){l.getOffset.call(this);this.chart.axisOffset[this.side]=0};a.getLinePath=function(a,k,l){a=this.pane.center;var p=this.chart,r=c(k,a[2]/2-this.offset),g=this.left||0,A=this.top||0;"undefined"===typeof l&&(l=this.horiz?0:this.center&&-this.center[3]/2);l&&(r+=l);this.isCircular||"undefined"!==
typeof k?(k=this.chart.renderer.symbols.arc(g+a[0],A+a[1],r,r,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),k.xBounds=[g+a[0]],k.yBounds=[A+a[1]-r]):(k=this.postTranslate(this.angleRad,r),k=[["M",this.center[0]+p.plotLeft,this.center[1]+p.plotTop],["L",k.x,k.y]]);return k};a.setAxisTranslation=function(){l.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-
this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)};a.beforeSetTickPositions=function(){this.autoConnect=this.isCircular&&"undefined"===typeof c(this.userMax,this.options.max)&&v(this.endAngleRad-this.startAngleRad)===v(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)};a.setAxisSize=function(){l.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);
var a=this.center=q([],this.pane.center);if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;else{var k=this.postTranslate(this.angleRad,a[3]/2);a[0]=k.x-this.chart.plotLeft;a[1]=k.y-this.chart.plotTop}this.len=this.width=this.height=(a[2]-a[3])*c(this.sector,1)/2}};a.getPosition=function(a,k){a=this.translate(a);return this.postTranslate(this.isCircular?a:this.angleRad,c(this.isCircular?k:0>a?0:a,this.center[2]/2)-this.offset)};a.postTranslate=function(c,a){var k=this.chart,p=this.center;
c=this.startAngleRad+c;return{x:k.plotLeft+p[0]+Math.cos(c)*a,y:k.plotTop+p[1]+Math.sin(c)*a}};a.getPlotBandPath=function(a,k,l){var p=function(g){if("string"===typeof g){var r=parseInt(g,10);H.test(g)&&(r=r*A/100);return r}return g},r=this.center,g=this.startAngleRad,A=r[2]/2,u=Math.min(this.offset,0),m=this.left||0,C=this.top||0,H=/%$/;var b=this.isCircular;var e=c(p(l.outerRadius),A),x=p(l.innerRadius);p=c(p(l.thickness),10);if("polygon"===this.options.gridLineInterpolation)u=this.getPlotLinePath({value:a}).concat(this.getPlotLinePath({value:k,
reverse:!0}));else{a=Math.max(a,this.min);k=Math.min(k,this.max);a=this.translate(a);k=this.translate(k);b||(e=a||0,x=k||0);if("circle"!==l.shape&&b)l=g+(a||0),g+=k||0;else{l=-Math.PI/2;g=1.5*Math.PI;var f=!0}e-=u;u=this.chart.renderer.symbols.arc(m+r[0],C+r[1],e,e,{start:Math.min(l,g),end:Math.max(l,g),innerR:c(x,e-(p-u)),open:f});b&&(b=(g+l)/2,m=m+r[0]+r[2]/2*Math.cos(b),u.xBounds=b>-Math.PI/2&&b<Math.PI/2?[m,this.chart.plotWidth]:[0,m],u.yBounds=[C+r[1]+r[2]/2*Math.sin(b)],u.yBounds[0]+=b>-Math.PI&&
0>b||b>Math.PI?-10:10)}return u};a.getCrosshairPosition=function(c,a,k){var p=c.value,r=this.pane.center;if(this.isCircular){if(e(p))c.point&&(g=c.point.shapeArgs||{},g.start&&(p=this.chart.inverted?this.translate(c.point.rectPlotY,!0):c.point.x));else{var g=c.chartX||0;var A=c.chartY||0;p=this.translate(Math.atan2(A-k,g-a)-this.startAngleRad,!0)}c=this.getPosition(p);g=c.x;A=c.y}else e(p)||(g=c.chartX,A=c.chartY),e(g)&&e(A)&&(k=r[1]+this.chart.plotTop,p=this.translate(Math.min(Math.sqrt(Math.pow(g-
a,2)+Math.pow(A-k,2)),r[2]/2)-r[3]/2,!0));return[p,g||0,A||0]};a.getPlotLinePath=function(c){var a=this,l=a.pane.center,p=a.chart,r=p.inverted,g=c.value,A=c.reverse,u=a.getPosition(g),m=a.pane.options.background?a.pane.options.background[0]||a.pane.options.background:{},C=m.innerRadius||"0%",b=m.outerRadius||"100%";m=l[0]+p.plotLeft;var e=l[1]+p.plotTop,f=u.x,D=u.y,h=a.height;u=l[3]/2;var q;c.isCrosshair&&(D=this.getCrosshairPosition(c,m,e),g=D[0],f=D[1],D=D[2]);if(a.isCircular)g=Math.sqrt(Math.pow(f-
m,2)+Math.pow(D-e,2)),A="string"===typeof C?k(C,1):C/g,p="string"===typeof b?k(b,1):b/g,l&&u&&(g=u/g,A<g&&(A=g),p<g&&(p=g)),l=[["M",m+A*(f-m),e-A*(e-D)],["L",f-(1-p)*(f-m),D+(1-p)*(e-D)]];else if((g=a.translate(g))&&(0>g||g>h)&&(g=0),"circle"===a.options.gridLineInterpolation)l=a.getLinePath(0,g,u);else if(l=[],p[r?"yAxis":"xAxis"].forEach(function(g){g.pane===a.pane&&(q=g)}),q)for(m=q.tickPositions,q.autoConnect&&(m=m.concat([m[0]])),A&&(m=m.slice().reverse()),g&&(g+=u),f=0;f<m.length;f++)e=q.getPosition(m[f],
g),l.push(f?["L",e.x,e.y]:["M",e.x,e.y]);return l};a.getTitlePosition=function(){var c=this.center,a=this.chart,k=this.options.title;return{x:a.plotLeft+c[0]+(k.x||0),y:a.plotTop+c[1]-{high:.5,middle:.25,low:0}[k.align]*c[2]+(k.y||0)}};a.createLabelCollector=function(){var c=this;return function(){if(c.isRadial&&c.tickPositions&&!0!==c.options.labels.allowOverlap)return c.tickPositions.map(function(a){return c.ticks[a]&&c.ticks[a].label}).filter(function(c){return!!c})}}};b.compose=function(e,f){a(e,
"init",function(c){var a=this.chart,k=a.inverted,p=a.angular,r=a.polar,g=this.isXAxis,A=this.coll,u=p&&g,m,C=a.options;c=c.userOptions.pane||0;c=this.pane=a.pane&&a.pane[c];if("colorAxis"===A)this.isRadial=!1;else{if(p){if(u?h.init(this):b.init(this),m=!g)this.defaultPolarOptions=b.defaultRadialGaugeOptions}else r&&(b.init(this),this.defaultPolarOptions=(m=this.horiz)?b.defaultCircularOptions:w("xAxis"===A?e.defaultOptions:e.defaultYAxisOptions,b.defaultRadialOptions),k&&"yAxis"===A&&(this.defaultPolarOptions.stackLabels=
e.defaultYAxisOptions.stackLabels));p||r?(this.isRadial=!0,C.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&a.labelCollectors.push(this.labelCollector)):this.isRadial=!1;c&&m&&(c.axis=this);this.isCircular=m}});a(e,"afterInit",function(){var a=this.chart,k=this.options,l=this.pane,p=l&&l.options;a.angular&&this.isXAxis||!l||!a.angular&&!a.polar||(this.angleRad=(k.angle||0)*Math.PI/180,this.startAngleRad=(p.startAngle-90)*Math.PI/180,
this.endAngleRad=(c(p.endAngle,p.startAngle+360)-90)*Math.PI/180,this.offset=k.offset||0)});a(e,"autoLabelAlign",function(c){this.isRadial&&(c.align=void 0,c.preventDefault())});a(e,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var c=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=c&&this.chart.labelCollectors.splice(c,1)}});a(e,"initialAxisTranslation",function(){this.isRadial&&this.beforeSetTickPositions()});a(f,"afterGetPosition",function(c){this.axis.getPosition&&
q(c.pos,this.axis.getPosition(this.pos))});a(f,"afterGetLabelPosition",function(a){var l=this.axis,e=this.label;if(e){var p=e.getBBox(),r=l.options.labels,g=r.y,A=20,u=r.align,m=(l.translate(this.pos)+l.startAngleRad+Math.PI/2)/Math.PI*180%360,C=Math.round(m),b="end",f=0>C?C+360:C,h=f,D=0,q=0,w=null===r.y?.3*-p.height:0;if(l.isRadial){var d=l.getPosition(this.pos,l.center[2]/2+k(c(r.distance,-25),l.center[2]/2,-l.center[2]/2));"auto"===r.rotation?e.attr({rotation:m}):null===g&&(g=l.chart.renderer.fontMetrics(e.styles&&
e.styles.fontSize).b-p.height/2);null===u&&(l.isCircular?(p.width>l.len*l.tickInterval/(l.max-l.min)&&(A=0),u=m>A&&m<180-A?"left":m>180+A&&m<360-A?"right":"center"):u="center",e.attr({align:u}));if("auto"===u&&2===l.tickPositions.length&&l.isCircular){90<f&&180>f?f=180-f:270<f&&360>=f&&(f=540-f);180<h&&360>=h&&(h=360-h);if(l.pane.options.startAngle===C||l.pane.options.startAngle===C+360||l.pane.options.startAngle===C-360)b="start";u=-90<=C&&90>=C||-360<=C&&-270>=C||270<=C&&360>=C?"start"===b?"right":
"left":"start"===b?"left":"right";70<h&&110>h&&(u="center");15>f||180<=f&&195>f?D=.3*p.height:15<=f&&35>=f?D="start"===b?0:.75*p.height:195<=f&&215>=f?D="start"===b?.75*p.height:0:35<f&&90>=f?D="start"===b?.25*-p.height:p.height:215<f&&270>=f&&(D="start"===b?p.height:.25*-p.height);15>h?q="start"===b?.15*-p.height:.15*p.height:165<h&&180>=h&&(q="start"===b?.15*p.height:.15*-p.height);e.attr({align:u});e.translate(q,D+w)}a.pos.x=d.x+r.x;a.pos.y=d.y+g}}});l(f.prototype,"getMarkPath",function(c,a,k,
p,r,g,A){var u=this.axis;u.isRadial?(c=u.getPosition(this.pos,u.center[2]/2+p),a=["M",a,k,"L",c.x,c.y]):a=c.call(this,a,k,p,r,g,A);return a})};b.defaultCircularOptions={gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0};b.defaultRadialGaugeOptions={labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",
tickWidth:2,title:{rotation:0},zIndex:2};b.defaultRadialOptions={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};return b}();f.compose(d,b);return f});z(d,"Series/AreaRange/AreaRangePoint.js",[d["Series/Area/AreaSeries.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"]],function(d,b,h){var f=this&&this.__extends||function(){var a=function(e,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,
a){c.__proto__=a}||function(c,a){for(var k in a)a.hasOwnProperty(k)&&(c[k]=a[k])};return a(e,b)};return function(e,b){function c(){this.constructor=e}a(e,b);e.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}}(),a=b.prototype,v=h.defined,e=h.isNumber;return function(b){function h(){var a=null!==b&&b.apply(this,arguments)||this;a.high=void 0;a.low=void 0;a.options=void 0;a.plotHigh=void 0;a.plotLow=void 0;a.plotHighX=void 0;a.plotLowX=void 0;a.plotX=void 0;a.series=void 0;return a}
f(h,b);h.prototype.setState=function(){var b=this.state,c=this.series,k=c.chart.polar;v(this.plotHigh)||(this.plotHigh=c.yAxis.toPixels(this.high,!0));v(this.plotLow)||(this.plotLow=this.plotY=c.yAxis.toPixels(this.low,!0));c.stateMarkerGraphic&&(c.lowerStateMarkerGraphic=c.stateMarkerGraphic,c.stateMarkerGraphic=c.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;k&&(this.plotX=this.plotHighX);a.setState.apply(this,arguments);this.state=b;this.plotY=this.plotLow;this.graphic=
this.lowerGraphic;k&&(this.plotX=this.plotLowX);c.stateMarkerGraphic&&(c.upperStateMarkerGraphic=c.stateMarkerGraphic,c.stateMarkerGraphic=c.lowerStateMarkerGraphic,c.lowerStateMarkerGraphic=void 0);a.setState.apply(this,arguments)};h.prototype.haloPath=function(){var b=this.series.chart.polar,c=[];this.plotY=this.plotLow;b&&(this.plotX=this.plotLowX);this.isInside&&(c=a.haloPath.apply(this,arguments));this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);this.isTopInside&&(c=c.concat(a.haloPath.apply(this,
arguments)));return c};h.prototype.destroyElements=function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return a.destroyElements.apply(this,arguments)};h.prototype.isValid=function(){return e(this.low)&&e(this.high)};return h}(d.prototype.pointClass)});z(d,"Series/AreaRange/AreaRangeSeries.js",[d["Series/AreaRange/AreaRangePoint.js"],d["Series/Area/AreaSeries.js"],d["Series/Column/ColumnSeries.js"],d["Core/Globals.js"],d["Core/Series/Series.js"],
d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h,f,a,v,e){var q=this&&this.__extends||function(){var c=function(a,p){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,g){c.__proto__=g}||function(c,g){for(var r in g)g.hasOwnProperty(r)&&(c[r]=g[r])};return c(a,p)};return function(a,p){function r(){this.constructor=a}c(a,p);a.prototype=null===p?Object.create(p):(r.prototype=p.prototype,new r)}}(),n=b.prototype,w=h.prototype,c=f.noop,k=a.prototype,l=e.defined,
t=e.extend,y=e.isArray,K=e.pick,L=e.merge;h=function(a){function e(){var p=null!==a&&a.apply(this,arguments)||this;p.data=void 0;p.options=void 0;p.points=void 0;p.lowerStateMarkerGraphic=void 0;p.xAxis=void 0;p.setStackedPoints=c;return p}q(e,a);e.prototype.toYData=function(c){return[c.low,c.high]};e.prototype.highToXY=function(c){var r=this.chart,g=this.xAxis.postTranslate(c.rectPlotX,this.yAxis.len-c.plotHigh);c.plotHighX=g.x-r.plotLeft;c.plotHigh=g.y-r.plotTop;c.plotLowX=c.plotX};e.prototype.translate=
function(){var c=this,r=c.yAxis,g=!!c.modifyValue;n.translate.apply(c);c.points.forEach(function(a){var u=a.high,m=a.plotY;a.isNull?a.plotY=null:(a.plotLow=m,a.plotHigh=r.translate(g?c.modifyValue(u,a):u,0,1,0,1),g&&(a.yBottom=a.plotHigh))});this.chart.polar&&this.points.forEach(function(g){c.highToXY(g);g.tooltipPos=[(g.plotHighX+g.plotLowX)/2,(g.plotHigh+g.plotLow)/2]})};e.prototype.getGraphPath=function(c){var a=[],g=[],p,u=n.getGraphPath;var m=this.options;var k=this.chart.polar,l=k&&!1!==m.connectEnds,
e=m.connectNulls,b=m.step;c=c||this.points;for(p=c.length;p--;){var f=c[p];var h=k?{plotX:f.rectPlotX,plotY:f.yBottom,doCurve:!1}:{plotX:f.plotX,plotY:f.plotY,doCurve:!1};f.isNull||l||e||c[p+1]&&!c[p+1].isNull||g.push(h);var d={polarPlotY:f.polarPlotY,rectPlotX:f.rectPlotX,yBottom:f.yBottom,plotX:K(f.plotHighX,f.plotX),plotY:f.plotHigh,isNull:f.isNull};g.push(d);a.push(d);f.isNull||l||e||c[p-1]&&!c[p-1].isNull||g.push(h)}c=u.call(this,c);b&&(!0===b&&(b="left"),m.step={left:"right",center:"center",
right:"left"}[b]);a=u.call(this,a);g=u.call(this,g);m.step=b;m=[].concat(c,a);!this.chart.polar&&g[0]&&"M"===g[0][0]&&(g[0]=["L",g[0][1],g[0][2]]);this.graphPath=m;this.areaPath=c.concat(g);m.isArea=!0;m.xMap=c.xMap;this.areaPath.xMap=c.xMap;return m};e.prototype.drawDataLabels=function(){var c=this.points,a=c.length,g,A=[],u=this.options.dataLabels,m,l=this.chart.inverted;if(y(u)){var e=u[0]||{enabled:!1};var b=u[1]||{enabled:!1}}else e=t({},u),e.x=u.xHigh,e.y=u.yHigh,b=t({},u),b.x=u.xLow,b.y=u.yLow;
if(e.enabled||this._hasPointLabels){for(g=a;g--;)if(m=c[g]){var f=e.inside?m.plotHigh<m.plotLow:m.plotHigh>m.plotLow;m.y=m.high;m._plotY=m.plotY;m.plotY=m.plotHigh;A[g]=m.dataLabel;m.dataLabel=m.dataLabelUpper;m.below=f;l?e.align||(e.align=f?"right":"left"):e.verticalAlign||(e.verticalAlign=f?"top":"bottom")}this.options.dataLabels=e;k.drawDataLabels&&k.drawDataLabels.apply(this,arguments);for(g=a;g--;)if(m=c[g])m.dataLabelUpper=m.dataLabel,m.dataLabel=A[g],delete m.dataLabels,m.y=m.low,m.plotY=m._plotY}if(b.enabled||
this._hasPointLabels){for(g=a;g--;)if(m=c[g])f=b.inside?m.plotHigh<m.plotLow:m.plotHigh>m.plotLow,m.below=!f,l?b.align||(b.align=f?"left":"right"):b.verticalAlign||(b.verticalAlign=f?"bottom":"top");this.options.dataLabels=b;k.drawDataLabels&&k.drawDataLabels.apply(this,arguments)}if(e.enabled)for(g=a;g--;)if(m=c[g])m.dataLabels=[m.dataLabelUpper,m.dataLabel].filter(function(g){return!!g});this.options.dataLabels=u};e.prototype.alignDataLabel=function(){w.alignDataLabel.apply(this,arguments)};e.prototype.drawPoints=
function(){var c=this.points.length,a;k.drawPoints.apply(this,arguments);for(a=0;a<c;){var g=this.points[a];g.origProps={plotY:g.plotY,plotX:g.plotX,isInside:g.isInside,negative:g.negative,zone:g.zone,y:g.y};g.lowerGraphic=g.graphic;g.graphic=g.upperGraphic;g.plotY=g.plotHigh;l(g.plotHighX)&&(g.plotX=g.plotHighX);g.y=g.high;g.negative=g.high<(this.options.threshold||0);g.zone=this.zones.length&&g.getZone();this.chart.polar||(g.isInside=g.isTopInside="undefined"!==typeof g.plotY&&0<=g.plotY&&g.plotY<=
this.yAxis.len&&0<=g.plotX&&g.plotX<=this.xAxis.len);a++}k.drawPoints.apply(this,arguments);for(a=0;a<c;)g=this.points[a],g.upperGraphic=g.graphic,g.graphic=g.lowerGraphic,t(g,g.origProps),delete g.origProps,a++};e.defaultOptions=L(b.defaultOptions,{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}});
return e}(b);t(h.prototype,{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,pointClass:d});v.registerSeriesType("arearange",h);"";return h});z(d,"Series/AreaSplineRange/AreaSplineRangeSeries.js",[d["Series/AreaRange/AreaRangeSeries.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h){var f=this&&this.__extends||function(){var a=function(e,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var k in a)a.hasOwnProperty(k)&&
(c[k]=a[k])};return a(e,b)};return function(e,b){function c(){this.constructor=e}a(e,b);e.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}}(),a=b.seriesTypes.spline,v=h.merge;h=h.extend;var e=function(a){function e(){var e=null!==a&&a.apply(this,arguments)||this;e.options=void 0;e.data=void 0;e.points=void 0;return e}f(e,a);e.defaultOptions=v(d.defaultOptions);return e}(d);h(e.prototype,{getPointSpline:a.prototype.getPointSpline});b.registerSeriesType("areasplinerange",e);"";return e});
z(d,"Series/ColumnRange/ColumnRangePoint.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b){var h=this&&this.__extends||function(){var a=function(b,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,e){a.__proto__=e}||function(a,e){for(var b in e)e.hasOwnProperty(b)&&(a[b]=e[b])};return a(b,e)};return function(b,e){function f(){this.constructor=b}a(b,e);b.prototype=null===e?Object.create(e):(f.prototype=e.prototype,new f)}}(),f=d.seriesTypes;d=f.column.prototype.pointClass;
b=b.extend;f=function(a){function b(){var e=null!==a&&a.apply(this,arguments)||this;e.series=void 0;e.options=void 0;e.barX=void 0;e.pointWidth=void 0;e.shapeArgs=void 0;e.shapeType=void 0;return e}h(b,a);return b}(f.arearange.prototype.pointClass);b(f.prototype,{setState:d.prototype.setState});return f});z(d,"Series/ColumnRange/ColumnRangeSeries.js",[d["Series/ColumnRange/ColumnRangePoint.js"],d["Core/Globals.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h,f){var a=
this&&this.__extends||function(){var c=function(a,k){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var p in a)a.hasOwnProperty(p)&&(c[p]=a[p])};return c(a,k)};return function(a,k){function e(){this.constructor=a}c(a,k);a.prototype=null===k?Object.create(k):(e.prototype=k.prototype,new e)}}();b=b.noop;var v=h.seriesTypes,e=v.arearange,q=v.column,n=q.prototype,w=e.prototype,c=f.clamp,k=f.merge,l=f.pick;f=f.extend;var t={pointRange:null,marker:null,
states:{hover:{halo:!1}}};v=function(b){function f(){var c=null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.points=void 0;c.options=void 0;return c}a(f,b);f.prototype.setOptions=function(){k(!0,arguments[0],{stacking:void 0});return w.setOptions.apply(this,arguments)};f.prototype.translate=function(){var a=this,k=a.yAxis,e=a.xAxis,p=e.startAngleRad,r,g=a.chart,A=a.xAxis.isRadial,u=Math.max(g.chartWidth,g.chartHeight)+999,m;n.translate.apply(a);a.points.forEach(function(b){var f=b.shapeArgs,
C=a.options.minPointLength;b.plotHigh=m=c(k.translate(b.high,0,1,0,1),-u,u);b.plotLow=c(b.plotY,-u,u);var h=m;var d=l(b.rectPlotY,b.plotY)-m;Math.abs(d)<C?(C-=d,d+=C,h-=C/2):0>d&&(d*=-1,h-=d);A?(r=b.barX+p,b.shapeType="arc",b.shapeArgs=a.polarArc(h+d,h,r,r+b.pointWidth)):(f.height=d,f.y=h,b.tooltipPos=g.inverted?[k.len+k.pos-g.plotLeft-h-d/2,e.len+e.pos-g.plotTop-f.x-f.width/2,d]:[e.left-g.plotLeft+f.x+f.width/2,k.pos-g.plotTop+h+d/2,d])})};f.prototype.crispCol=function(){return n.crispCol.apply(this,
arguments)};f.prototype.drawPoints=function(){return n.drawPoints.apply(this,arguments)};f.prototype.drawTracker=function(){return n.drawTracker.apply(this,arguments)};f.prototype.getColumnMetrics=function(){return n.getColumnMetrics.apply(this,arguments)};f.prototype.pointAttribs=function(){return n.pointAttribs.apply(this,arguments)};f.prototype.adjustForMissingColumns=function(){return n.adjustForMissingColumns.apply(this,arguments)};f.prototype.animate=function(){return n.animate.apply(this,arguments)};
f.prototype.translate3dPoints=function(){return n.translate3dPoints.apply(this,arguments)};f.prototype.translate3dShapes=function(){return n.translate3dShapes.apply(this,arguments)};f.defaultOptions=k(q.defaultOptions,e.defaultOptions,t);return f}(e);f(v.prototype,{directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:b,getSymbol:b,polarArc:function(){return n.polarArc.apply(this,arguments)},pointClass:d});h.registerSeriesType("columnrange",v);"";return v});z(d,"Series/ColumnPyramid/ColumnPyramidSeries.js",
[d["Series/Column/ColumnSeries.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h){var f=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return a(b,c)};return function(b,c){function k(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),a=d.prototype,v=h.clamp,e=h.merge,
q=h.pick;h=function(b){function h(){var c=null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}f(h,b);h.prototype.translate=function(){var c=this,b=c.chart,e=c.options,f=c.dense=2>c.closestPointRange*c.xAxis.transA;f=c.borderWidth=q(e.borderWidth,f?0:1);var h=c.yAxis,d=e.threshold,w=c.translatedThreshold=h.getThreshold(d),n=q(e.minPointLength,5),x=c.getColumnMetrics(),p=x.width,r=c.barW=Math.max(p,1+2*f),g=c.pointXOffset=x.offset;b.inverted&&(w-=.5);e.pointPadding&&
(r=Math.ceil(r));a.translate.apply(c);c.points.forEach(function(a){var u=q(a.yBottom,w),m=999+Math.abs(u),k=v(a.plotY,-m,h.len+m);m=a.plotX+g;var A=r/2,f=Math.min(k,u);u=Math.max(k,u)-f;var l;a.barX=m;a.pointWidth=p;a.tooltipPos=b.inverted?[h.len+h.pos-b.plotLeft-k,c.xAxis.len-m-A,u]:[m+A,k+h.pos-b.plotTop,u];k=d+(a.total||a.y);"percent"===e.stacking&&(k=d+(0>a.y)?-100:100);k=h.toPixels(k,!0);var D=(l=b.plotHeight-k-(b.plotHeight-w))?A*(f-k)/l:0;var x=l?A*(f+u-k)/l:0;l=m-D+A;D=m+D+A;var t=m+x+A;x=
m-x+A;var y=f-n;var G=f+u;0>a.y&&(y=f,G=f+u+n);b.inverted&&(t=b.plotWidth-f,l=k-(b.plotWidth-w),D=A*(k-t)/l,x=A*(k-(t-u))/l,l=m+A+D,D=l-2*D,t=m-x+A,x=m+x+A,y=f,G=f+u-n,0>a.y&&(G=f+u+n));a.shapeType="path";a.shapeArgs={x:l,y:y,width:D-l,height:u,d:[["M",l,y],["L",D,y],["L",t,G],["L",x,G],["Z"]]}})};h.defaultOptions=e(d.defaultOptions,{});return h}(d);b.registerSeriesType("columnpyramid",h);"";return h});z(d,"Series/Gauge/GaugePoint.js",[d["Core/Series/SeriesRegistry.js"]],function(d){var b=this&&this.__extends||
function(){var b=function(f,a){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e])};return b(f,a)};return function(f,a){function h(){this.constructor=f}b(f,a);f.prototype=null===a?Object.create(a):(h.prototype=a.prototype,new h)}}();return function(h){function f(){var a=null!==h&&h.apply(this,arguments)||this;a.options=void 0;a.series=void 0;a.shapeArgs=void 0;return a}b(f,h);f.prototype.setState=function(a){this.state=
a};return f}(d.series.prototype.pointClass)});z(d,"Series/Gauge/GaugeSeries.js",[d["Series/Gauge/GaugePoint.js"],d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h,f,a){var v=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function k(){this.constructor=
c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}();b=b.noop;var e=f.series,q=f.seriesTypes.column,n=a.clamp,w=a.isNumber,c=a.extend,k=a.merge,l=a.pick,t=a.pInt;a=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.points=void 0;c.options=void 0;c.yAxis=void 0;return c}v(c,a);c.prototype.translate=function(){var a=this.yAxis,c=this.options,b=a.center;this.generatePoints();this.points.forEach(function(p){var r=k(c.dial,p.dial),g=t(l(r.radius,
"80%"))*b[2]/200,e=t(l(r.baseLength,"70%"))*g/100,u=t(l(r.rearLength,"10%"))*g/100,m=r.baseWidth||3,f=r.topWidth||1,h=c.overshoot,d=a.startAngleRad+a.translate(p.y,null,null,null,!0);if(w(h)||!1===c.wrap)h=w(h)?h/180*Math.PI:0,d=n(d,a.startAngleRad-h,a.endAngleRad+h);d=180*d/Math.PI;p.shapeType="path";p.shapeArgs={d:r.path||[["M",-u,-m/2],["L",e,-m/2],["L",g,-f/2],["L",g,f/2],["L",e,m/2],["L",-u,m/2],["Z"]],translateX:b[0],translateY:b[1],rotation:d};p.plotX=b[0];p.plotY=b[1]})};c.prototype.drawPoints=
function(){var a=this,c=a.chart,b=a.yAxis.center,e=a.pivot,r=a.options,g=r.pivot,A=c.renderer;a.points.forEach(function(g){var b=g.graphic,u=g.shapeArgs,e=u.d,p=k(r.dial,g.dial);b?(b.animate(u),u.d=e):g.graphic=A[g.shapeType](u).attr({rotation:u.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group);if(!c.styledMode)g.graphic[b?"animate":"attr"]({stroke:p.borderColor||"none","stroke-width":p.borderWidth||0,fill:p.backgroundColor||h.neutralColor100})});e?e.animate({translateX:b[0],translateY:b[1]}):
(a.pivot=A.circle(0,0,l(g.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(b[0],b[1]).add(a.group),c.styledMode||a.pivot.attr({"stroke-width":g.borderWidth||0,stroke:g.borderColor||h.neutralColor20,fill:g.backgroundColor||h.neutralColor100}))};c.prototype.animate=function(a){var c=this;a||c.points.forEach(function(a){var b=a.graphic;b&&(b.attr({rotation:180*c.yAxis.startAngleRad/Math.PI}),b.animate({rotation:a.shapeArgs.rotation},c.options.animation))})};c.prototype.render=function(){this.group=
this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);e.prototype.render.call(this);this.group.clip(this.chart.clipRect)};c.prototype.setData=function(a,c){e.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();l(c,!0)&&this.chart.redraw()};c.prototype.hasData=function(){return!!this.points.length};c.defaultOptions=k(e.defaultOptions,{dataLabels:{borderColor:h.neutralColor20,borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,
verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1});return c}(e);c(a.prototype,{angular:!0,directTouch:!0,drawGraph:b,drawTracker:q.prototype.drawTracker,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,pointClass:d,trackerGroups:["group","dataLabelsGroup"]});f.registerSeriesType("gauge",a);"";return a});z(d,"Series/BoxPlot/BoxPlotSeries.js",[d["Series/Column/ColumnSeries.js"],d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],
function(d,b,h,f,a){var v=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function e(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}();b=b.noop;var e=a.extend,q=a.merge,n=a.pick;a=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=
void 0;c.options=void 0;c.points=void 0;return c}v(c,a);c.prototype.pointAttribs=function(){return{}};c.prototype.translate=function(){var c=this.yAxis,b=this.pointArrayMap;a.prototype.translate.apply(this);this.points.forEach(function(a){b.forEach(function(b){null!==a[b]&&(a[b+"Plot"]=c.translate(a[b],0,1,0,1))});a.plotHigh=a.highPlot})};c.prototype.drawPoints=function(){var a=this,c=a.options,b=a.chart,e=b.renderer,f,h,d,q,p,r,g=0,A,u,m,C,H=!1!==a.doQuartiles,v,w=a.options.whiskerLength;a.points.forEach(function(k){var l=
k.graphic,t=l?"animate":"attr",D=k.shapeArgs,x={},I={},y={},J={},B=k.color||a.color;"undefined"!==typeof k.plotY&&(A=Math.round(D.width),u=Math.floor(D.x),m=u+A,C=Math.round(A/2),f=Math.floor(H?k.q1Plot:k.lowPlot),h=Math.floor(H?k.q3Plot:k.lowPlot),d=Math.floor(k.highPlot),q=Math.floor(k.lowPlot),l||(k.graphic=l=e.g("point").add(a.group),k.stem=e.path().addClass("highcharts-boxplot-stem").add(l),w&&(k.whiskers=e.path().addClass("highcharts-boxplot-whisker").add(l)),H&&(k.box=e.path(void 0).addClass("highcharts-boxplot-box").add(l)),
k.medianShape=e.path(void 0).addClass("highcharts-boxplot-median").add(l)),b.styledMode||(I.stroke=k.stemColor||c.stemColor||B,I["stroke-width"]=n(k.stemWidth,c.stemWidth,c.lineWidth),I.dashstyle=k.stemDashStyle||c.stemDashStyle||c.dashStyle,k.stem.attr(I),w&&(y.stroke=k.whiskerColor||c.whiskerColor||B,y["stroke-width"]=n(k.whiskerWidth,c.whiskerWidth,c.lineWidth),y.dashstyle=k.whiskerDashStyle||c.whiskerDashStyle||c.dashStyle,k.whiskers.attr(y)),H&&(x.fill=k.fillColor||c.fillColor||B,x.stroke=c.lineColor||
B,x["stroke-width"]=c.lineWidth||0,x.dashstyle=k.boxDashStyle||c.boxDashStyle||c.dashStyle,k.box.attr(x)),J.stroke=k.medianColor||c.medianColor||B,J["stroke-width"]=n(k.medianWidth,c.medianWidth,c.lineWidth),J.dashstyle=k.medianDashStyle||c.medianDashStyle||c.dashStyle,k.medianShape.attr(J)),r=k.stem.strokeWidth()%2/2,g=u+C+r,l=[["M",g,h],["L",g,d],["M",g,f],["L",g,q]],k.stem[t]({d:l}),H&&(r=k.box.strokeWidth()%2/2,f=Math.floor(f)+r,h=Math.floor(h)+r,u+=r,m+=r,l=[["M",u,h],["L",u,f],["L",m,f],["L",
m,h],["L",u,h],["Z"]],k.box[t]({d:l})),w&&(r=k.whiskers.strokeWidth()%2/2,d+=r,q+=r,v=/%$/.test(w)?C*parseFloat(w)/100:w/2,l=[["M",g-v,d],["L",g+v,d],["M",g-v,q],["L",g+v,q]],k.whiskers[t]({d:l})),p=Math.round(k.medianPlot),r=k.medianShape.strokeWidth()%2/2,p+=r,l=[["M",u,p],["L",m,p]],k.medianShape[t]({d:l}))})};c.prototype.toYData=function(a){return[a.low,a.q1,a.median,a.q3,a.high]};c.defaultOptions=q(d.defaultOptions,{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},
whiskerLength:"50%",fillColor:h.backgroundColor,lineWidth:1,medianWidth:2,whiskerWidth:2});return c}(d);e(a.prototype,{pointArrayMap:["low","q1","median","q3","high"],pointValKey:"high",drawDataLabels:b,setStackedPoints:b});f.registerSeriesType("boxplot",a);"";return a});z(d,"Series/ErrorBar/ErrorBarSeries.js",[d["Series/BoxPlot/BoxPlotSeries.js"],d["Series/Column/ColumnSeries.js"],d["Core/Color/Palette.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h,f,a){var v=this&&
this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function e(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),e=f.seriesTypes.arearange,q=a.merge;a=a.extend;var n=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;
c.points=void 0;return c}v(c,a);c.prototype.getColumnMetrics=function(){return this.linkedParent&&this.linkedParent.columnMetrics||b.prototype.getColumnMetrics.call(this)};c.prototype.drawDataLabels=function(){var a=this.pointValKey;e&&(e.prototype.drawDataLabels.call(this),this.data.forEach(function(c){c.y=c[a]}))};c.prototype.toYData=function(a){return[a.low,a.high]};c.defaultOptions=q(d.defaultOptions,{color:h.neutralColor100,grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
whiskerWidth:null});return c}(d);a(n.prototype,{pointArrayMap:["low","high"],pointValKey:"high",doQuartiles:!1});f.registerSeriesType("errorbar",n);"";return n});z(d,"Core/Axis/WaterfallAxis.js",[d["Extensions/Stacking.js"],d["Core/Utilities.js"]],function(d,b){var h=b.addEvent,f=b.objectEach,a;(function(a){function b(){var a=this.waterfall.stacks;a&&(a.changed=!1,delete a.alreadyChanged)}function q(){var a=this.options.stackLabels;a&&a.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}
function v(){for(var a=this.axes,c=this.series,b=c.length;b--;)c[b].options.stacking&&(a.forEach(function(a){a.isXAxis||(a.waterfall.stacks.changed=!0)}),b=0)}function w(){this.waterfall||(this.waterfall=new c(this))}var c=function(){function a(a){this.axis=a;this.stacks={changed:!1}}a.prototype.renderStackTotals=function(){var a=this.axis,c=a.waterfall.stacks,b=a.stacking&&a.stacking.stackTotalGroup,e=new d(a,a.options.stackLabels,!1,0,void 0);this.dummyStackItem=e;f(c,function(a){f(a,function(a){e.total=
a.stackTotal;a.label&&(e.label=a.label);d.prototype.render.call(e,b);a.label=e.label;delete e.label})});e.total=null};return a}();a.Composition=c;a.compose=function(a,c){h(a,"init",w);h(a,"afterBuildStacks",b);h(a,"afterRender",q);h(c,"beforeRedraw",v)}})(a||(a={}));return a});z(d,"Series/Waterfall/WaterfallPoint.js",[d["Series/Column/ColumnSeries.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"]],function(d,b,h){var f=this&&this.__extends||function(){var a=function(b,f){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,f)};return function(b,f){function e(){this.constructor=b}a(b,f);b.prototype=null===f?Object.create(f):(e.prototype=f.prototype,new e)}}(),a=h.isNumber;return function(h){function e(){var a=null!==h&&h.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}f(e,h);e.prototype.getClassName=function(){var a=b.prototype.getClassName.call(this);this.isSum?
a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a};e.prototype.isValid=function(){return a(this.y)||this.isSum||!!this.isIntermediateSum};return e}(d.prototype.pointClass)});z(d,"Series/Waterfall/WaterfallSeries.js",[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Color/Palette.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"],d["Core/Axis/WaterfallAxis.js"],d["Series/Waterfall/WaterfallPoint.js"]],function(d,b,h,f,a,v,e){var q=this&&this.__extends||
function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var c in g)g.hasOwnProperty(c)&&(a[c]=g[c])};return a(c,b)};return function(c,b){function r(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(r.prototype=b.prototype,new r)}}(),n=f.seriesTypes,w=n.column,c=n.line,k=a.arrayMax,l=a.arrayMin,t=a.correctFloat;n=a.extend;var y=a.merge,B=a.objectEach,z=a.pick;a=function(a){function b(){var c=null!==a&&
a.apply(this,arguments)||this;c.chart=void 0;c.data=void 0;c.options=void 0;c.points=void 0;c.stackedYNeg=void 0;c.stackedYPos=void 0;c.stackKey=void 0;c.xData=void 0;c.yAxis=void 0;c.yData=void 0;return c}q(b,a);b.prototype.generatePoints=function(){var a;w.prototype.generatePoints.apply(this);var c=0;for(a=this.points.length;c<a;c++){var g=this.points[c];var b=this.processedYData[c];if(g.isIntermediateSum||g.isSum)g.y=t(b)}};b.prototype.translate=function(){var a=this.options,c=this.yAxis,g,b=z(a.minPointLength,
5),e=b/2,m=a.threshold,f=a.stacking,k=c.waterfall.stacks[this.stackKey];w.prototype.translate.apply(this);var h=g=m;var l=this.points;var d=0;for(a=l.length;d<a;d++){var q=l[d];var v=this.processedYData[d];var t=q.shapeArgs;var n=[0,v];var x=q.y;if(f){if(k){n=k[d];if("overlap"===f){var y=n.stackState[n.stateIndex--];y=0<=x?y:y-x;Object.hasOwnProperty.call(n,"absolutePos")&&delete n.absolutePos;Object.hasOwnProperty.call(n,"absoluteNeg")&&delete n.absoluteNeg}else 0<=x?(y=n.threshold+n.posTotal,n.posTotal-=
x):(y=n.threshold+n.negTotal,n.negTotal-=x,y-=x),!n.posTotal&&Object.hasOwnProperty.call(n,"absolutePos")&&(n.posTotal=n.absolutePos,delete n.absolutePos),!n.negTotal&&Object.hasOwnProperty.call(n,"absoluteNeg")&&(n.negTotal=n.absoluteNeg,delete n.absoluteNeg);q.isSum||(n.connectorThreshold=n.threshold+n.stackTotal);c.reversed?(v=0<=x?y-x:y+x,x=y):(v=y,x=y-x);q.below=v<=z(m,0);t.y=c.translate(v,0,1,0,1);t.height=Math.abs(t.y-c.translate(x,0,1,0,1));if(x=c.waterfall.dummyStackItem)x.x=d,x.label=k[d].label,
x.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[d],this.stackedYPos[d])}}else y=Math.max(h,h+x)+n[0],t.y=c.translate(y,0,1,0,1),q.isSum?(t.y=c.translate(n[1],0,1,0,1),t.height=Math.min(c.translate(n[0],0,1,0,1),c.len)-t.y):q.isIntermediateSum?(0<=x?(v=n[1]+g,x=g):(v=g,x=n[1]+g),c.reversed&&(v^=x,x^=v,v^=x),t.y=c.translate(v,0,1,0,1),t.height=Math.abs(t.y-Math.min(c.translate(x,0,1,0,1),c.len)),g+=n[1]):(t.height=0<v?c.translate(h,0,1,0,1)-t.y:c.translate(h,0,1,0,1)-c.translate(h-v,
0,1,0,1),h+=v,q.below=h<z(m,0)),0>t.height&&(t.y+=t.height,t.height*=-1);q.plotY=t.y=Math.round(t.y)-this.borderWidth%2/2;t.height=Math.max(Math.round(t.height),.001);q.yBottom=t.y+t.height;t.height<=b&&!q.isNull?(t.height=b,t.y-=e,q.plotY=t.y,q.minPointLengthOffset=0>q.y?-e:e):(q.isNull&&(t.width=0),q.minPointLengthOffset=0);t=q.plotY+(q.negative?t.height:0);this.chart.inverted?q.tooltipPos[0]=c.len-t:q.tooltipPos[1]=t}};b.prototype.processData=function(c){var b=this.options,g=this.yData,e=b.data,
u=g.length,m=b.threshold||0,f,k,p,h,d;for(d=k=f=p=h=0;d<u;d++){var l=g[d];var q=e&&e[d]?e[d]:{};"sum"===l||q.isSum?g[d]=t(k):"intermediateSum"===l||q.isIntermediateSum?(g[d]=t(f),f=0):(k+=l,f+=l);p=Math.min(k,p);h=Math.max(k,h)}a.prototype.processData.call(this,c);b.stacking||(this.dataMin=p+m,this.dataMax=h)};b.prototype.toYData=function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y};b.prototype.updateParallelArrays=function(c,b){a.prototype.updateParallelArrays.call(this,c,b);
if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=null};b.prototype.pointAttribs=function(a,c){var g=this.options.upColor;g&&!a.options.color&&(a.color=0<a.y?g:null);a=w.prototype.pointAttribs.call(this,a,c);delete a.dashstyle;return a};b.prototype.getGraphPath=function(){return[["M",0,0]]};b.prototype.getCrispPath=function(){var a=this.data,c=this.yAxis,g=a.length,b=Math.round(this.graph.strokeWidth())%2/2,e=Math.round(this.borderWidth)%2/2,m=this.xAxis.reversed,f=this.yAxis.reversed,
k=this.options.stacking,d=[],h;for(h=1;h<g;h++){var l=a[h].shapeArgs;var q=a[h-1];var t=a[h-1].shapeArgs;var v=c.waterfall.stacks[this.stackKey];var n=0<q.y?-t.height:0;v&&t&&l&&(v=v[h-1],k?(v=v.connectorThreshold,n=Math.round(c.translate(v,0,1,0,1)+(f?n:0))-b):n=t.y+q.minPointLengthOffset+e-b,d.push(["M",(t.x||0)+(m?0:t.width||0),n],["L",(l.x||0)+(m?l.width||0:0),n]));t&&d.length&&(!k&&0>q.y&&!f||0<q.y&&f)&&(d[d.length-2][2]+=t.height,d[d.length-1][2]+=t.height)}return d};b.prototype.drawGraph=function(){c.prototype.drawGraph.call(this);
this.graph.attr({d:this.getCrispPath()})};b.prototype.setStackedPoints=function(){function a(a,g,c,b){if(z)for(c;c<z;c++)w.stackState[c]+=b;else w.stackState[0]=a,z=w.stackState.length;w.stackState.push(w.stackState[z-1]+g)}var c=this.options,g=this.yAxis.waterfall.stacks,b=c.threshold,e=b||0,m=e,f=this.stackKey,k=this.xData,d=k.length,h,l,q;this.yAxis.stacking.usePercentage=!1;var t=l=q=e;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var v=g.changed;(h=g.alreadyChanged)&&0>h.indexOf(f)&&
(v=!0);g[f]||(g[f]={});h=g[f];for(var n=0;n<d;n++){var x=k[n];if(!h[x]||v)h[x]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:v&&h[x]?h[x].label:void 0};var w=h[x];var y=this.yData[n];0<=y?w.posTotal+=y:w.negTotal+=y;var B=c.data[n];x=w.absolutePos=w.posTotal;var K=w.absoluteNeg=w.negTotal;w.stackTotal=x+K;var z=w.stackState.length;B&&B.isIntermediateSum?(a(q,l,0,q),q=l,l=b,e^=m,m^=e,e^=m):B&&B.isSum?(a(b,t,z),e=b):(a(e,y,0,t),B&&(t+=y,l+=y));w.stateIndex++;w.threshold=
e;e+=w.stackTotal}g.changed=!1;g.alreadyChanged||(g.alreadyChanged=[]);g.alreadyChanged.push(f)}};b.prototype.getExtremes=function(){var a=this.options.stacking;if(a){var c=this.yAxis;c=c.waterfall.stacks;var g=this.stackedYNeg=[];var b=this.stackedYPos=[];"overlap"===a?B(c[this.stackKey],function(a){g.push(l(a.stackState));b.push(k(a.stackState))}):B(c[this.stackKey],function(a){g.push(a.negTotal+a.threshold);b.push(a.posTotal+a.threshold)});return{dataMin:l(g),dataMax:k(b)}}return{dataMin:this.dataMin,
dataMax:this.dataMax}};b.defaultOptions=y(w.defaultOptions,{dataLabels:{inside:!0},lineWidth:1,lineColor:h.neutralColor80,dashStyle:"Dot",borderColor:h.neutralColor80,states:{hover:{lineWidthPlus:0}}});return b}(w);n(a.prototype,{pointValKey:"y",showLine:!0,pointClass:e});f.registerSeriesType("waterfall",a);v.compose(b.Axis,d);"";return a});z(d,"Series/Polygon/PolygonSeries.js",[d["Core/Globals.js"],d["Mixins/LegendSymbol.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,
b,h,f){var a=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function e(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}();d=d.noop;var v=h.series,e=h.seriesTypes,q=e.area,n=e.scatter;e=f.extend;var w=f.merge;f=function(c){function b(){var a=null!==c&&c.apply(this,
arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}a(b,c);b.prototype.getGraphPath=function(){for(var a=v.prototype.getGraphPath.call(this),c=a.length+1;c--;)(c===a.length||"M"===a[c][0])&&0<c&&a.splice(c,0,["Z"]);return this.areaPath=a};b.prototype.drawGraph=function(){this.options.fillColor=this.color;q.prototype.drawGraph.call(this)};b.defaultOptions=w(n.defaultOptions,{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},
trackByArea:!0});return b}(n);e(f.prototype,{type:"polygon",drawLegendSymbol:b.drawRectangle,drawTracker:v.prototype.drawTracker,setStackedPoints:d});h.registerSeriesType("polygon",f);"";return f});z(d,"Series/Bubble/BubblePoint.js",[d["Core/Series/Point.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h){var f=this&&this.__extends||function(){var a=function(b,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)b.hasOwnProperty(e)&&
(a[e]=b[e])};return a(b,e)};return function(b,e){function f(){this.constructor=b}a(b,e);b.prototype=null===e?Object.create(e):(f.prototype=e.prototype,new f)}}();h=h.extend;b=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.options=void 0;b.series=void 0;return b}f(b,a);b.prototype.haloPath=function(a){return d.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)};return b}(b.seriesTypes.scatter.prototype.pointClass);h(b.prototype,{ttBelow:!1});return b});
z(d,"Series/Bubble/BubbleLegend.js",[d["Core/Chart/Chart.js"],d["Core/Color/Color.js"],d["Core/Globals.js"],d["Core/Legend.js"],d["Core/Color/Palette.js"],d["Core/Series/Series.js"],d["Core/Utilities.js"]],function(d,b,h,f,a,v,e){var q=b.parse,n=h.noop;b=e.addEvent;var w=e.arrayMax,c=e.arrayMin,k=e.isNumber,l=e.merge,t=e.objectEach,y=e.pick,B=e.setOptions,z=e.stableSort,F=e.wrap;"";B({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,
connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});B=function(){function b(a,c){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=
this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=n;this.init(a,c)}b.prototype.init=function(a,c){this.options=a;this.visible=!0;this.chart=c.chart;this.legend=c};b.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};b.prototype.drawLegendSymbol=function(a){var c=this.chart,g=this.options,b=y(a.options.itemDistance,20),e=g.ranges;var m=g.connectorDistance;this.fontMetrics=c.renderer.fontMetrics(g.labels.style.fontSize.toString()+
"px");e&&e.length&&k(e[0].value)?(z(e,function(a,c){return c.value-a.value}),this.ranges=e,this.setOptions(),this.render(),c=this.getMaxLabelSize(),e=this.ranges[0].radius,a=2*e,m=m-e+c.width,m=0<m?m:0,this.maxLabel=c,this.movementX="left"===g.labels.align?m:0,this.legendItemWidth=a+m+b,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};b.prototype.setOptions=function(){var a=this.ranges,c=this.options,g=this.chart.series[c.seriesIndex],b=this.legend.baseline,e={"z-index":c.zIndex,
"stroke-width":c.borderWidth},m={"z-index":c.zIndex,"stroke-width":c.connectorWidth},f=this.getLabelStyles(),k=g.options.marker.fillOpacity,d=this.chart.styledMode;a.forEach(function(r,u){d||(e.stroke=y(r.borderColor,c.borderColor,g.color),e.fill=y(r.color,c.color,1!==k?q(g.color).setOpacity(k).get("rgba"):g.color),m.stroke=y(r.connectorColor,c.connectorColor,g.color));a[u].radius=this.getRangeRadius(r.value);a[u]=l(a[u],{center:a[0].radius-a[u].radius+b});d||l(!0,a[u],{bubbleStyle:l(!1,e),connectorStyle:l(!1,
m),labelStyle:f})},this)};b.prototype.getLabelStyles=function(){var c=this.options,b={},g="left"===c.labels.align,e=this.legend.options.rtl;t(c.labels.style,function(a,c){"color"!==c&&"fontSize"!==c&&"z-index"!==c&&(b[c]=a)});return l(!1,b,{"font-size":c.labels.style.fontSize,fill:y(c.labels.style.color,a.neutralColor100),"z-index":c.zIndex,align:e||g?"right":"left"})};b.prototype.getRangeRadius=function(a){var c=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,
c.ranges[c.ranges.length-1].value,c.ranges[0].value,c.minSize,c.maxSize,a)};b.prototype.render=function(){var a=this.chart.renderer,c=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=c&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);
this.hideOverlappingLabels()};b.prototype.renderRange=function(a){var c=this.options,g=c.labels,b=this.chart.renderer,e=this.symbols,f=e.labels,k=a.center,d=Math.abs(a.radius),h=c.connectorDistance||0,l=g.align,p=g.style.fontSize;h=this.legend.options.rtl||"left"===l?-h:h;g=c.connectorWidth;var q=this.ranges[0].radius||0,t=k-d-c.borderWidth/2+g/2;p=p/2-(this.fontMetrics.h-p)/2;var n=b.styledMode;"center"===l&&(h=0,c.connectorDistance=0,a.labelStyle.align="center");l=t+c.labels.y;var v=q+h+c.labels.x;
e.bubbleItems.push(b.circle(q,k+((t%1?1:.5)-(g%2?0:.5)),d).attr(n?{}:a.bubbleStyle).addClass((n?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(c.className||"")).add(this.legendSymbol));e.connectors.push(b.path(b.crispLine([["M",q,t],["L",q+h,t]],c.connectorWidth)).attr(n?{}:a.connectorStyle).addClass((n?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(c.connectorClassName||"")).add(this.legendSymbol));a=b.text(this.formatLabel(a),
v,l+p).attr(n?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(c.labels.className||"")).add(this.legendSymbol);f.push(a);a.placed=!0;a.alignAttr={x:v,y:l+p}};b.prototype.getMaxLabelSize=function(){var a,c;this.symbols.labels.forEach(function(g){c=g.getBBox(!0);a=a?c.width>a.width?c:a:c});return a||{}};b.prototype.formatLabel=function(a){var c=this.options,g=c.labels.formatter;c=c.labels.format;var b=this.chart.numberFormatter;return c?e.format(c,a):g?g.call(a):b(a.value,1)};b.prototype.hideOverlappingLabels=
function(){var a=this.chart,c=this.symbols;!this.options.labels.allowOverlap&&c&&(a.hideOverlappingLabels(c.labels),c.labels.forEach(function(a,b){a.newOpacity?a.newOpacity!==a.oldOpacity&&c.connectors[b].show():c.connectors[b].hide()}))};b.prototype.getRanges=function(){var a=this.legend.bubbleLegend,b=a.options.ranges,g,e=Number.MAX_VALUE,f=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(g=a.zData.filter(k),g.length&&(e=y(a.options.zMin,Math.min(e,Math.max(c(g),
!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),f=y(a.options.zMax,Math.max(f,w(g)))))});var m=e===f?[{value:f}]:[{value:e},{value:(e+f)/2},{value:f,autoRanges:!0}];b.length&&b[0].radius&&m.reverse();m.forEach(function(a,c){b&&b[c]&&(m[c]=l(!1,b[c],a))});return m};b.prototype.predictBubbleSizes=function(){var a=this.chart,c=this.fontMetrics,g=a.legend.options,b="horizontal"===g.layout,e=b?a.legend.lastLineHeight:0,f=a.plotSizeX,k=a.plotSizeY,d=a.series[this.options.seriesIndex];
a=Math.ceil(d.minPxSize);var h=Math.ceil(d.maxPxSize);d=d.options.maxSize;var l=Math.min(k,f);if(g.floating||!/%$/.test(d))c=h;else if(d=parseFloat(d),c=(l+e-c.h/2)*d/100/(d/100+1),b&&k-c>=f||!b&&f-c>=k)c=h;return[a,Math.ceil(c)]};b.prototype.updateRanges=function(a,c){var g=this.legend.options.bubbleLegend;g.minSize=a;g.maxSize=c;g.ranges=this.getRanges()};b.prototype.correctSizes=function(){var a=this.legend,c=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(c.maxPxSize)-this.options.maxSize)&&
(this.updateRanges(this.options.minSize,c.maxPxSize),a.render())};return b}();b(f,"afterGetAllItems",function(a){var c=this.bubbleLegend,b=this.options,g=b.bubbleLegend,e=this.chart.getVisibleBubbleSeriesIndex();c&&c.ranges&&c.ranges.length&&(g.ranges.length&&(g.autoRanges=!!g.ranges[0].autoRanges),this.destroyItem(c));0<=e&&b.enabled&&g.enabled&&(g.seriesIndex=e,this.bubbleLegend=new h.BubbleLegend(g,this),this.bubbleLegend.addToLegend(a.allItems))});d.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=
this.series,c=0;c<a.length;){if(a[c]&&a[c].isBubble&&a[c].visible&&a[c].zData.length)return c;c++}return-1};f.prototype.getLinesHeights=function(){var a=this.allItems,c=[],b=a.length,g,e=0;for(g=0;g<b;g++)if(a[g].legendItemHeight&&(a[g].itemHeight=a[g].legendItemHeight),a[g]===a[b-1]||a[g+1]&&a[g]._legendItemPos[1]!==a[g+1]._legendItemPos[1]){c.push({height:0});var f=c[c.length-1];for(e;e<=g;e++)a[e].itemHeight>f.height&&(f.height=a[e].itemHeight);f.step=g}return c};f.prototype.retranslateItems=function(a){var c,
b,g,e=this.options.rtl,f=0;this.allItems.forEach(function(m,k){c=m.legendGroup.translateX;b=m._legendItemPos[1];if((g=m.movementX)||e&&m.ranges)g=e?c-m.options.maxSize/2:c+g,m.legendGroup.attr({translateX:g});k>a[f].step&&f++;m.legendGroup.attr({translateY:Math.round(b+a[f].height/2)});m._legendItemPos[1]=b+a[f].height/2})};b(v,"legendItemClick",function(){var a=this.chart,c=this.visible,b=this.chart.legend;b&&b.bubbleLegend&&(this.visible=!c,this.ignoreSeries=c,a=0<=a.getVisibleBubbleSeriesIndex(),
b.bubbleLegend.visible!==a&&(b.update({bubbleLegend:{enabled:a}}),b.bubbleLegend.visible=a),this.visible=c)});F(d.prototype,"drawChartBox",function(a,c,b){var g=this.legend,e=0<=this.getVisibleBubbleSeriesIndex();if(g&&g.options.enabled&&g.bubbleLegend&&g.options.bubbleLegend.autoRanges&&e){var f=g.bubbleLegend.options;e=g.bubbleLegend.predictBubbleSizes();g.bubbleLegend.updateRanges(e[0],e[1]);f.placed||(g.group.placed=!1,g.allItems.forEach(function(a){a.legendGroup.translateY=null}));g.render();
this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();f.placed||(a.setScale(),a.updateNames(),t(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});f.placed=!0;this.getMargins();a.call(this,c,b);g.bubbleLegend.correctSizes();g.retranslateItems(g.getLinesHeights())}else a.call(this,c,b),g&&g.options.enabled&&g.bubbleLegend&&(g.render(),g.retranslateItems(g.getLinesHeights()))});h.BubbleLegend=B;return h.BubbleLegend});z(d,"Series/Bubble/BubbleSeries.js",[d["Core/Axis/Axis.js"],d["Series/Bubble/BubblePoint.js"],
d["Core/Color/Color.js"],d["Core/Globals.js"],d["Core/Series/Series.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,b,h,f,a,v,e){var q=this&&this.__extends||function(){var a=function(c,g){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var g in c)c.hasOwnProperty(g)&&(a[g]=c[g])};return a(c,g)};return function(c,g){function b(){this.constructor=c}a(c,g);c.prototype=null===g?Object.create(g):(b.prototype=g.prototype,
new b)}}(),n=h.parse;h=f.noop;var w=v.seriesTypes;f=w.column;var c=w.scatter,k=e.arrayMax,l=e.arrayMin,t=e.clamp,y=e.extend,B=e.isNumber,z=e.merge,F=e.pick,x=e.pInt;e=function(b){function e(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.maxPxSize=void 0;a.minPxSize=void 0;a.options=void 0;a.points=void 0;a.radii=void 0;a.yData=void 0;a.zData=void 0;return a}q(e,b);e.prototype.animate=function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var c=
a.graphic;c&&c.width&&(this.hasRendered||c.attr({x:a.plotX,y:a.plotY,width:1,height:1}),c.animate(this.markerAttribs(a),this.options.animation))},this)};e.prototype.getRadii=function(a,c,b){var g=this.zData,e=this.yData,f=b.minPxSize,k=b.maxPxSize,d=[];var h=0;for(b=g.length;h<b;h++){var u=g[h];d.push(this.getRadius(a,c,f,k,u,e[h]))}this.radii=d};e.prototype.getRadius=function(a,c,b,e,f,k){var g=this.options,m="width"!==g.sizeBy,d=g.zThreshold,h=c-a,l=.5;if(null===k||null===f)return null;if(B(f)){g.sizeByAbsoluteValue&&
(f=Math.abs(f-d),h=Math.max(c-d,Math.abs(a-d)),a=0);if(f<a)return b/2-1;0<h&&(l=(f-a)/h)}m&&0<=l&&(l=Math.sqrt(l));return Math.ceil(b+l*(e-b))/2};e.prototype.hasData=function(){return!!this.processedXData.length};e.prototype.pointAttribs=function(c,b){var g=this.options.marker.fillOpacity;c=a.prototype.pointAttribs.call(this,c,b);1!==g&&(c.fill=n(c.fill).setOpacity(g).get("rgba"));return c};e.prototype.translate=function(){var a,c=this.data,e=this.radii;b.prototype.translate.call(this);for(a=c.length;a--;){var f=
c[a];var k=e?e[a]:0;B(k)&&k>=this.minPxSize/2?(f.marker=y(f.marker,{radius:k,width:2*k,height:2*k}),f.dlBox={x:f.plotX-k,y:f.plotY-k,width:2*k,height:2*k}):f.shapeArgs=f.plotY=f.dlBox=void 0}};e.defaultOptions=z(c.defaultOptions,{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},
tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});return e}(c);y(e.prototype,{alignDataLabel:f.prototype.alignDataLabel,applyZones:h,bubblePadding:!0,buildKDTree:h,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:b,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});d.prototype.beforePadding=function(){var a=this,c=this.len,g=this.chart,b=0,e=c,f=this.isXAxis,d=f?"xData":
"yData",h=this.min,q={},n=Math.min(g.plotWidth,g.plotHeight),v=Number.MAX_VALUE,w=-Number.MAX_VALUE,y=this.max-h,z=c/y,G=[];this.series.forEach(function(c){var b=c.options;!c.bubblePadding||!c.visible&&g.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,G.push(c),f&&(["minSize","maxSize"].forEach(function(a){var c=b[a],g=/%$/.test(c);c=x(c);q[a]=g?n*c/100:c}),c.minPxSize=q.minSize,c.maxPxSize=Math.max(q.maxSize,q.minSize),c=c.zData.filter(B),c.length&&(v=F(b.zMin,t(l(c),!1===b.displayNegative?
b.zThreshold:-Number.MAX_VALUE,v)),w=F(b.zMax,Math.max(w,k(c))))))});G.forEach(function(c){var g=c[d],k=g.length;f&&c.getRadii(v,w,c);if(0<y)for(;k--;)if(B(g[k])&&a.dataMin<=g[k]&&g[k]<=a.max){var m=c.radii?c.radii[k]:0;b=Math.min((g[k]-h)*z-m,b);e=Math.max((g[k]-h)*z+m,e)}});G.length&&0<y&&!this.logarithmic&&(e-=c,z*=(c+Math.max(0,b)-Math.min(e,c))/c,[["min","userMin",b],["max","userMax",e]].forEach(function(c){"undefined"===typeof F(a.options[c[0]],a[c[1]])&&(a[c[0]]+=c[2]/z)}))};v.registerSeriesType("bubble",
e);"";"";return e});z(d,"Series/PackedBubble/PackedBubblePoint.js",[d["Core/Chart/Chart.js"],d["Core/Series/Point.js"],d["Core/Series/SeriesRegistry.js"]],function(d,b,h){var f=this&&this.__extends||function(){var a=function(b,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e])};return a(b,e)};return function(b,e){function f(){this.constructor=b}a(b,e);b.prototype=null===e?Object.create(e):(f.prototype=
e.prototype,new f)}}();return function(a){function h(){var b=null!==a&&a.apply(this,arguments)||this;b.degree=NaN;b.mass=NaN;b.radius=NaN;b.options=void 0;b.series=void 0;b.value=null;return b}f(h,a);h.prototype.destroy=function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return b.prototype.destroy.apply(this,arguments)};h.prototype.firePointEvent=function(){var a=this.series.options;if(this.isParentNode&&a.parentNode){var f=a.allowPointSelect;
a.allowPointSelect=a.parentNode.allowPointSelect;b.prototype.firePointEvent.apply(this,arguments);a.allowPointSelect=f}else b.prototype.firePointEvent.apply(this,arguments)};h.prototype.select=function(){var a=this.series.chart;this.isParentNode?(a.getSelectedPoints=a.getSelectedParentNodes,b.prototype.select.apply(this,arguments),a.getSelectedPoints=d.prototype.getSelectedPoints):b.prototype.select.apply(this,arguments)};return h}(h.seriesTypes.bubble.prototype.pointClass)});z(d,"Series/Networkgraph/DraggableNodes.js",
[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,b,h){var f=h.addEvent;b.dragNodesMixin={onMouseDown:function(a,b){b=this.chart.pointer.normalize(b);a.fixedPosition={chartX:b.chartX,chartY:b.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,b){if(a.fixedPosition&&a.inDragMode){var e=this.chart;b=e.pointer.normalize(b);var f=a.fixedPosition.chartX-b.chartX,d=a.fixedPosition.chartY-b.chartY;b=e.graphLayoutsLookup;if(5<Math.abs(f)||5<Math.abs(d))f=
a.fixedPosition.plotX-f,d=a.fixedPosition.plotY-d,e.isInsidePlot(f,d)&&(a.plotX=f,a.plotY=d,a.hasDragged=!0,this.redrawHalo(a),b.forEach(function(a){a.restartSimulation()}))}},onMouseUp:function(a,b){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};f(d,"load",
function(){var a=this,b,e,d;a.container&&(b=f(a.container,"mousedown",function(b){var h=a.hoverPoint;h&&h.series&&h.series.hasDraggableNodes&&h.series.options.draggable&&(h.series.onMouseDown(h,b),e=f(a.container,"mousemove",function(a){return h&&h.series&&h.series.onMouseMove(h,a)}),d=f(a.container.ownerDocument,"mouseup",function(a){e();d();return h&&h.series&&h.series.onMouseUp(h,a)}))}));f(a,"destroy",function(){b()})})});z(d,"Series/Networkgraph/Integrations.js",[d["Core/Globals.js"]],function(d){d.networkgraphIntegrations=
{verlet:{attractiveForceFunction:function(b,d){return(d-b)/b},repulsiveForceFunction:function(b,d){return(d-b)/b*(d>b?1:0)},barycenter:function(){var b=this.options.gravitationalConstant,d=this.barycenter.xFactor,f=this.barycenter.yFactor;d=(d-(this.box.left+this.box.width)/2)*b;f=(f-(this.box.top+this.box.height)/2)*b;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=d/a.mass/a.degree,a.plotY-=f/a.mass/a.degree)})},repulsive:function(b,d,f){d=d*this.diffTemperature/b.mass/b.degree;b.fixedPosition||
(b.plotX+=f.x*d,b.plotY+=f.y*d)},attractive:function(b,d,f){var a=b.getMass(),h=-f.x*d*this.diffTemperature;d=-f.y*d*this.diffTemperature;b.fromNode.fixedPosition||(b.fromNode.plotX-=h*a.fromNode/b.fromNode.degree,b.fromNode.plotY-=d*a.fromNode/b.fromNode.degree);b.toNode.fixedPosition||(b.toNode.plotX+=h*a.toNode/b.toNode.degree,b.toNode.plotY+=d*a.toNode/b.toNode.degree)},integrate:function(b,d){var f=-b.options.friction,a=b.options.maxSpeed,h=(d.plotX+d.dispX-d.prevX)*f;f*=d.plotY+d.dispY-d.prevY;
var e=Math.abs,q=e(h)/(h||1);e=e(f)/(f||1);h=q*Math.min(a,Math.abs(h));f=e*Math.min(a,Math.abs(f));d.prevX=d.plotX+d.dispX;d.prevY=d.plotY+d.dispY;d.plotX+=h;d.plotY+=f;d.temperature=b.vectorLength({x:h,y:f})},getK:function(b){return Math.pow(b.box.width*b.box.height/b.nodes.length,.5)}},euler:{attractiveForceFunction:function(b,d){return b*b/d},repulsiveForceFunction:function(b,d){return d*d/b},barycenter:function(){var b=this.options.gravitationalConstant,d=this.barycenter.xFactor,f=this.barycenter.yFactor;
this.nodes.forEach(function(a){if(!a.fixedPosition){var h=a.getDegree();h*=1+h/2;a.dispX+=(d-a.plotX)*b*h/a.degree;a.dispY+=(f-a.plotY)*b*h/a.degree}})},repulsive:function(b,d,f,a){b.dispX+=f.x/a*d/b.degree;b.dispY+=f.y/a*d/b.degree},attractive:function(b,d,f,a){var h=b.getMass(),e=f.x/a*d;d*=f.y/a;b.fromNode.fixedPosition||(b.fromNode.dispX-=e*h.fromNode/b.fromNode.degree,b.fromNode.dispY-=d*h.fromNode/b.fromNode.degree);b.toNode.fixedPosition||(b.toNode.dispX+=e*h.toNode/b.toNode.degree,b.toNode.dispY+=
d*h.toNode/b.toNode.degree)},integrate:function(b,d){d.dispX+=d.dispX*b.options.friction;d.dispY+=d.dispY*b.options.friction;var f=d.temperature=b.vectorLength({x:d.dispX,y:d.dispY});0!==f&&(d.plotX+=d.dispX/f*Math.min(Math.abs(d.dispX),b.temperature),d.plotY+=d.dispY/f*Math.min(Math.abs(d.dispY),b.temperature))},getK:function(b){return Math.pow(b.box.width*b.box.height/b.nodes.length,.3)}}}});z(d,"Series/Networkgraph/QuadTree.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,b){b=b.extend;
var h=d.QuadTreeNode=function(b){this.box=b;this.boxSize=Math.min(b.width,b.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};b(h.prototype,{insert:function(b,a){this.isInternal?this.nodes[this.getBoxPosition(b)].insert(b,a-1):(this.isEmpty=!1,this.body?a?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,a-1),this.body=!0),this.nodes[this.getBoxPosition(b)].insert(b,a-1)):(a=new h({top:b.plotX,left:b.plotY,width:.1,
height:.1}),a.body=b,a.isInternal=!1,this.nodes.push(a)):(this.isInternal=!1,this.body=b))},updateMassAndCenter:function(){var b=0,a=0,d=0;this.isInternal?(this.nodes.forEach(function(e){e.isEmpty||(b+=e.mass,a+=e.plotX*e.mass,d+=e.plotY*e.mass)}),a/=b,d/=b):this.body&&(b=this.body.mass,a=this.body.plotX,d=this.body.plotY);this.mass=b;this.plotX=a;this.plotY=d},divideBox:function(){var b=this.box.width/2,a=this.box.height/2;this.nodes[0]=new h({left:this.box.left,top:this.box.top,width:b,height:a});
this.nodes[1]=new h({left:this.box.left+b,top:this.box.top,width:b,height:a});this.nodes[2]=new h({left:this.box.left+b,top:this.box.top+a,width:b,height:a});this.nodes[3]=new h({left:this.box.left,top:this.box.top+a,width:b,height:a})},getBoxPosition:function(b){var a=b.plotY<this.box.top+this.box.height/2;return b.plotX<this.box.left+this.box.width/2?a?0:3:a?1:2}});d=d.QuadTree=function(b,a,d,e){this.box={left:b,top:a,width:d,height:e};this.maxDepth=25;this.root=new h(this.box,"0");this.root.isInternal=
!0;this.root.isRoot=!0;this.root.divideBox()};b(d.prototype,{insertNodes:function(b){b.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(b,a,d){var e;b||(b=this.root);b===this.root&&a&&(e=a(b));!1!==e&&(b.nodes.forEach(function(b){if(b.isInternal){a&&(e=a(b));if(!1===e)return;this.visitNodeRecursive(b,a,d)}else b.body&&a&&a(b.body);d&&d(b)},this),b===this.root&&d&&d(b))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(b){b.updateMassAndCenter()})}})});
z(d,"Series/Networkgraph/Layouts.js",[d["Core/Chart/Chart.js"],d["Core/Animation/AnimationUtilities.js"],d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,b,h,f){var a=b.setAnimation;b=f.addEvent;var v=f.clamp,e=f.defined,q=f.extend,n=f.isFunction,w=f.pick;h.layouts={"reingold-fruchterman":function(){}};q(h.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=
h.networkgraphIntegrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=w(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=w(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},updateSimulation:function(a){this.enableSimulation=w(a,this.options.enableSimulation)},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&
(this.initPositions(),a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(b);this.enableSimulation&&this.step()},step:function(){var a=this,b=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(c){a[c+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;
a.systemTemperature=a.getSystemTemperature();a.enableSimulation&&(b.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&h.win.cancelAnimationFrame(a.simulation),a.simulation=h.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&h.win.cancelAnimationFrame(this.simulation)},setArea:function(a,b,d,e){this.box={left:a,top:b,width:d,height:e}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},
addElementsToCollection:function(a,b){a.forEach(function(a){-1===b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,b){a=b.indexOf(a);-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),
this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(a){this.maxIterations=w(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=
new h.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;n(a)?(a.call(this),this.nodes.forEach(function(a){e(a.prevX)||(a.prevX=a.plotX);e(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(c){c.linksFrom.forEach(function(c){q[c.toNode.id]||(q[c.toNode.id]=!0,h.push(c.toNode),
a(c.toNode))})}var b=this.box,d=this.nodes,e=2*Math.PI/(d.length+1),f=d.filter(function(a){return 0===a.linksTo.length}),h=[],q={},n=this.options.initialPositionRadius;f.forEach(function(c){h.push(c);a(c)});h.length?d.forEach(function(a){-1===h.indexOf(a)&&h.push(a)}):h=d;h.forEach(function(a,c){a.plotX=a.prevX=w(a.plotX,b.width/2+n*Math.cos(c*e));a.plotY=a.prevY=w(a.plotY,b.height/2+n*Math.sin(c*e));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}
var b=this.box,d=this.nodes,e=d.length+1;d.forEach(function(c,d){c.plotX=c.prevX=w(c.plotX,b.width*a(d));c.plotY=c.prevY=w(c.plotY,b.height*a(e+d));c.dispX=0;c.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=0,b=0,d=0;this.nodes.forEach(function(c){b+=c.plotX*c.mass;d+=c.plotY*c.mass;a+=c.mass});return this.barycenter={x:b,y:d,xFactor:b/a,
yFactor:d/a}},barnesHutApproximation:function(a,b){var c=this.getDistXY(a,b),d=this.vectorLength(c);if(a!==b&&0!==d)if(b.isInternal)if(b.boxSize/d<this.options.theta&&0!==d){var e=this.repulsiveForce(d,this.k);this.force("repulsive",a,e*b.mass,c,d);var f=!1}else f=!0;else e=this.repulsiveForce(d,this.k),this.force("repulsive",a,e*b.mass,c,d);return f},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(c){a.quadTree.visitNodeRecursive(null,function(b){return a.barnesHutApproximation(c,
b)})}):a.nodes.forEach(function(c){a.nodes.forEach(function(b){if(c!==b&&!c.fixedPosition){var d=a.getDistXY(c,b);var e=a.vectorLength(d);if(0!==e){var f=a.repulsiveForce(e,a.k);a.force("repulsive",c,f*b.mass,d,e)}}})})},attractiveForces:function(){var a=this,b,d,e;a.links.forEach(function(c){c.fromNode&&c.toNode&&(b=a.getDistXY(c.fromNode,c.toNode),d=a.vectorLength(b),0!==d&&(e=a.attractiveForce(d,a.k),a.force("attractive",c,e,b,d)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(c){c.fixedPosition||
(a.integration.integrate(a,c),a.applyLimitBox(c,a.box),c.dispX=0,c.dispY=0)})},applyLimitBox:function(a,b){var c=a.radius;a.plotX=v(a.plotX,b.left+c,b.width-c);a.plotY=v(a.plotY,b.top+c,b.height-c)},coolDown:function(a,b,d){return a-b*d},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+
a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);return this.vectorLength(a)},getDistXY:function(a,b){var c=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});b(d,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});b(d,"render",function(){function c(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),d=!1,b=!0)}var b=!1;if(this.graphLayoutsLookup){a(!1,
this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!d;){var d=!0;this.graphLayoutsLookup.forEach(c)}b&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});b(d,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),this.redraw())});b(d,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});z(d,"Series/PackedBubble/PackedBubbleComposition.js",
[d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,b,h){var f=b.layouts["reingold-fruchterman"],a=h.addEvent,v=h.extendClass,e=h.pick;d.prototype.getSelectedParentNodes=function(){var a=[];this.series.forEach(function(b){b.parentNode&&b.parentNode.selected&&a.push(b.parentNode)});return a};b.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,b,d,c){return Math.min(a,(d.marker.radius+c.marker.radius)/2)},barycenter:function(){var a=this,b=a.options.gravitationalConstant,
d=a.box,c=a.nodes,e,f;c.forEach(function(h){a.options.splitSeries&&!h.isParentNode?(e=h.series.parentNode.plotX,f=h.series.parentNode.plotY):(e=d.width/2,f=d.height/2);h.fixedPosition||(h.plotX-=(h.plotX-e)*b/(h.mass*Math.sqrt(c.length)),h.plotY-=(h.plotY-f)*b/(h.mass*Math.sqrt(c.length)))})},repulsive:function(a,b,d,c){var e=b*this.diffTemperature/a.mass/a.degree;b=d.x*e;d=d.y*e;a.fixedPosition||(a.plotX+=b,a.plotY+=d);c.fixedPosition||(c.plotX-=b,c.plotY-=d)},integrate:b.networkgraphIntegrations.verlet.integrate,
getK:b.noop};b.layouts.packedbubble=v(f,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,b=a.box,d=a.nodes,c=2*Math.PI/(d.length+1),f,h,t=a.options.initialPositionRadius;d.forEach(function(d,k){a.options.splitSeries&&!d.isParentNode?(f=d.series.parentNode.plotX,h=d.series.parentNode.plotY):(f=b.width/2,h=b.height/2);d.plotX=d.prevX=e(d.plotX,f+t*Math.cos(d.index||k*c));d.plotY=d.prevY=e(d.plotY,h+
t*Math.sin(d.index||k*c));d.dispX=0;d.dispY=0})},repulsiveForces:function(){var a=this,b,d,c,e=a.options.bubblePadding;a.nodes.forEach(function(f){f.degree=f.mass;f.neighbours=0;a.nodes.forEach(function(h){b=0;f===h||f.fixedPosition||!a.options.seriesInteraction&&f.series!==h.series||(c=a.getDistXY(f,h),d=a.vectorLength(c)-(f.marker.radius+h.marker.radius+e),0>d&&(f.degree+=.01,f.neighbours++,b=a.repulsiveForce(-d/Math.sqrt(f.neighbours),a.k,f,h)),a.force("repulsive",f,b*h.mass,c,h,d))})})},applyLimitBox:function(a){if(this.options.splitSeries&&
!a.isParentNode&&this.options.parentNodeLimit){var b=this.getDistXY(a,a.series.parentNode);var d=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(b);0>d&&d>-2*a.marker.radius&&(a.plotX-=.01*b.x,a.plotY-=.01*b.y)}f.prototype.applyLimitBox.apply(this,arguments)}});a(d,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints})});z(d,"Series/PackedBubble/PackedBubbleSeries.js",[d["Core/Color/Color.js"],d["Core/Globals.js"],d["Series/PackedBubble/PackedBubblePoint.js"],d["Core/Series/SeriesRegistry.js"],
d["Core/Utilities.js"]],function(d,b,h,f,a){var v=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function g(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(g.prototype=c.prototype,new g)}}(),e=d.parse,q=f.series,n=f.seriesTypes.bubble,w=a.addEvent,c=a.clamp,k=a.defined,l=a.extend,t=a.fireEvent,
y=a.isArray,z=a.isNumber,B=a.merge,F=a.pick,x=b.dragNodesMixin;d=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.layout=void 0;b.options=void 0;b.points=void 0;b.xData=void 0;return b}v(d,a);d.prototype.accumulateAllPoints=function(a){var b=a.chart,c=[],g,d;for(g=0;g<b.series.length;g++)if(a=b.series[g],a.is("packedbubble")&&a.visible||!b.options.chart.ignoreHiddenSeries)for(d=0;d<a.yData.length;d++)c.push([null,null,a.yData[d],a.index,d,{id:d,
marker:{radius:0}}]);return c};d.prototype.addLayout=function(){var a=this.options.layoutAlgorithm,c=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,e=this.chart.options.chart;c||(this.chart.graphLayoutsStorage=c={},this.chart.graphLayoutsLookup=d=[]);var f=c[a.type];f||(a.enableSimulation=k(e.forExport)?!e.forExport:a.enableSimulation,c[a.type]=f=new b.layouts[a.type],f.init(a),d.splice(f.index,0,f));this.layout=f;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=
1});f.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);f.addElementsToCollection([this],f.series);f.addElementsToCollection(this.points,f.nodes)};d.prototype.addSeriesLayout=function(){var a=this.options.layoutAlgorithm,c=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,e=B(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var f=c[a.type+"-series"];f||(c[a.type+"-series"]=f=new b.layouts[a.type],f.init(e),d.splice(f.index,0,f));this.parentNodeLayout=
f;this.createParentNodes()};d.prototype.calculateParentRadius=function(){var a=this.seriesBox();this.parentNodeRadius=c(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)};d.prototype.calculateZExtremes=function(){var a=this.options.zMin,b=this.options.zMax,c=Infinity,d=-Infinity;if(a&&b)return[a,
b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){k(a)&&(a>d&&(d=a),a<c&&(c=a))})});a=F(a,c);b=F(b,d);return[a,b]};d.prototype.checkOverlap=function(a,b){var c=a[0]-b[0],g=a[1]-b[1];return-.001>Math.sqrt(c*c+g*g)-Math.abs(a[2]+b[2])};d.prototype.createParentNodes=function(){var a=this,b=a.chart,c=a.parentNodeLayout,d,e=a.parentNode,f=a.pointClass;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(b){b.seriesIndex===
a.index&&(d=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);d||(e||(e=(new f).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(e.plotX=a.parentNode.plotX,e.plotY=a.parentNode.plotY),a.parentNode=e,c.addElementsToCollection([a],c.series),c.addElementsToCollection([e],c.nodes))};d.prototype.deferLayout=function(){var a=this.options.layoutAlgorithm;this.visible&&
(this.addLayout(),a.splitSeries&&this.addSeriesLayout())};d.prototype.destroy=function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&this.parentNodeLayout&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));q.prototype.destroy.apply(this,arguments)};d.prototype.drawDataLabels=
function(){var a=this.options.dataLabels.textPath,b=this.points;q.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,q.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)};d.prototype.drawGraph=function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;
b={fill:b.fillColor||e(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};var c=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",c,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();c=B({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},
b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(c)}};d.prototype.drawTracker=function(){var b=this.parentNode;a.prototype.drawTracker.call(this);if(b){var c=y(b.dataLabels)?b.dataLabels:b.dataLabel?[b.dataLabel]:[];b.graphic&&(b.graphic.element.point=b);c.forEach(function(a){a.div?a.div.point=b:a.element.point=b})}};d.prototype.getPointRadius=function(){var a=this,b=a.chart,d=a.options,e=d.useSimulation,
f=Math.min(b.plotWidth,b.plotHeight),h={},k=[],r=b.allDataPoints,l,n,p,q;["minSize","maxSize"].forEach(function(a){var b=parseInt(d[a],10),c=/%$/.test(d[a]);h[a]=c?f*b/100:b*Math.sqrt(r.length)});b.minRadius=l=h.minSize/Math.sqrt(r.length);b.maxRadius=n=h.maxSize/Math.sqrt(r.length);var t=e?a.calculateZExtremes():[l,n];(r||[]).forEach(function(b,g){p=e?c(b[2],t[0],t[1]):b[2];q=a.getRadius(t[0],t[1],l,n,p);0===q&&(q=null);r[g][2]=q;k.push(q)});a.radii=k};d.prototype.init=function(){q.prototype.init.apply(this,
arguments);this.eventsToUnbind.push(w(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)}));return this};d.prototype.onMouseUp=function(a){if(a.fixedPosition&&!a.removed){var b,c,d=this.layout,g=this.parentNodeLayout;g&&d.options.dragBetweenSeries&&g.nodes.forEach(function(g){a&&a.marker&&g!==a.series.parentNode&&(b=d.getDistXY(a,g),c=d.vectorLength(b)-g.marker.radius-a.marker.radius,0>c&&(g.series.addPoint(B(a.options,{plotX:a.plotX,plotY:a.plotY}),
!1),d.removeElementFromCollection(a,d.nodes),a.remove()))});x.onMouseUp.apply(this,arguments)}};d.prototype.placeBubbles=function(a){var b=this.checkOverlap,c=this.positionBubble,d=[],g=1,e=0,f=0;var h=[];var k;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){d.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(d.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),k=2;k<a.length;k++)a[k][2]=a[k][2]||1,h=c(d[g][e],d[g-1][f],a[k]),b(h,d[g][0])?(d.push([]),f=0,d[g+1].push(c(d[g][e],d[g][0],
a[k])),g++,e=0):1<g&&d[g-1][f+1]&&b(h,d[g-1][f+1])?(f++,d[g].push(c(d[g][e],d[g-1][f],a[k])),e++):(e++,d[g].push(h));this.chart.stages=d;this.chart.rawPositions=[].concat.apply([],d);this.resizeRadius();h=this.chart.rawPositions}return h};d.prototype.positionBubble=function(a,b,c){var d=Math.sqrt,g=Math.asin,e=Math.acos,f=Math.pow,h=Math.abs;d=d(f(a[0]-b[0],2)+f(a[1]-b[1],2));e=e((f(d,2)+f(c[2]+b[2],2)-f(c[2]+a[2],2))/(2*(c[2]+b[2])*d));g=g(h(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+e+g*(0>(a[0]-b[0])*
(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]};d.prototype.render=function(){var a=[];q.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(b){y(b.dataLabels)&&b.dataLabels.forEach(function(b){a.push(b)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))};d.prototype.resizeRadius=function(){var a=this.chart,b=a.rawPositions,c=Math.min,d=Math.max,e=a.plotLeft,f=a.plotTop,h=a.plotHeight,
k=a.plotWidth,r,l,n;var p=r=Number.POSITIVE_INFINITY;var q=l=Number.NEGATIVE_INFINITY;for(n=0;n<b.length;n++){var t=b[n][2];p=c(p,b[n][0]-t);q=d(q,b[n][0]+t);r=c(r,b[n][1]-t);l=d(l,b[n][1]+t)}n=[q-p,l-r];c=c.apply([],[(k-e)/n[0],(h-f)/n[1]]);if(1e-10<Math.abs(c-1)){for(n=0;n<b.length;n++)b[n][2]*=c;this.placeBubbles(b)}else a.diffY=h/2+f-r-(l-r)/2,a.diffX=k/2+e-p-(q-p)/2};d.prototype.seriesBox=function(){var a=this.chart,b=Math.max,c=Math.min,d,e=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+
a.plotHeight];this.data.forEach(function(a){k(a.plotX)&&k(a.plotY)&&a.marker.radius&&(d=a.marker.radius,e[0]=c(e[0],a.plotX-d),e[1]=b(e[1],a.plotX+d),e[2]=c(e[2],a.plotY-d),e[3]=b(e[3],a.plotY+d))});return z(e.width/e.height)?e:null};d.prototype.setVisible=function(){var a=this;q.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,
a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(b){a.layout.removeElementFromCollection(b,a.layout.nodes)}))};d.prototype.translate=function(){var a=this.chart,b=this.data,c=this.index,d,e=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();k(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(e)var f=
a.allDataPoints;else f=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(d=0;d<f.length;d++)if(f[d][3]===c){var h=b[f[d][4]];var r=f[d][2];e||(h.plotX=f[d][0]-a.plotLeft+a.diffX,h.plotY=f[d][1]-a.plotTop+a.diffY);h.marker=l(h.marker,{radius:r,width:2*r,height:2*r});h.radius=r}e&&this.deferLayout();t(this,"afterTranslate")};d.defaultOptions=B(n.defaultOptions,{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,
parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,
fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}});return d}(n);l(d.prototype,{alignDataLabel:q.prototype.alignDataLabel,axisTypes:[],directTouch:!0,forces:["barycenter","repulsive"],hasDraggableNodes:!0,isCartesian:!1,noSharedTooltip:!0,onMouseDown:x.onMouseDown,onMouseMove:x.onMouseMove,pointArrayMap:["value"],pointClass:h,pointValKey:"value",
redrawHalo:x.redrawHalo,requireSorting:!1,searchPoint:b.noop,trackerGroups:["group","dataLabelsGroup","parentNodesGroup"]});f.registerSeriesType("packedbubble",d);"";"";return d});z(d,"Extensions/Polar.js",[d["Core/Animation/AnimationUtilities.js"],d["Core/Chart/Chart.js"],d["Core/Globals.js"],d["Extensions/Pane.js"],d["Core/Pointer.js"],d["Core/Series/Series.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Renderer/SVG/SVGRenderer.js"],d["Core/Utilities.js"]],function(d,b,h,f,a,v,e,q,n){var w=d.animObject;
e=e.seriesTypes;var c=n.addEvent,k=n.defined,l=n.find,t=n.isNumber,y=n.pick,z=n.splat,B=n.uniqueKey;d=n.wrap;var F=v.prototype;a=a.prototype;F.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};F.getConnectors=function(a,b,c,d){var g=d?1:0;var e=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>e-1?a.length-(1+g):e-1;g=e+1>a.length-1?g:e+1;var f=a[b];g=a[g];var h=f.plotX;
f=f.plotY;var k=g.plotX;var r=g.plotY;g=a[e].plotX;e=a[e].plotY;h=(1.5*g+h)/2.5;f=(1.5*e+f)/2.5;k=(1.5*g+k)/2.5;var l=(1.5*e+r)/2.5;r=Math.sqrt(Math.pow(h-g,2)+Math.pow(f-e,2));var u=Math.sqrt(Math.pow(k-g,2)+Math.pow(l-e,2));h=Math.atan2(f-e,h-g);l=Math.PI/2+(h+Math.atan2(l-e,k-g))/2;Math.abs(h-l)>Math.PI/2&&(l-=Math.PI);h=g+Math.cos(l)*r;f=e+Math.sin(l)*r;k=g+Math.cos(Math.PI+l)*u;l=e+Math.sin(Math.PI+l)*u;g={rightContX:k,rightContY:l,leftContX:h,leftContY:f,plotX:g,plotY:e};c&&(g.prevPointCont=
this.getConnectors(a,b,!1,d));return g};F.toXY=function(a){var b=this.chart,c=this.xAxis;var d=this.yAxis;var e=a.plotX,f=a.plotY,h=a.series,k=b.inverted,l=a.y,r=k?e:d.len-f;k&&h&&!h.isRadialBar&&(a.plotY=f="number"===typeof l?d.translate(l)||0:0);a.rectPlotX=e;a.rectPlotY=f;d.center&&(r+=d.center[3]/2);d=k?d.postTranslate(f,r):c.postTranslate(e,r);a.plotX=a.polarPlotX=d.x-b.plotLeft;a.plotY=a.polarPlotY=d.y-b.plotTop;this.kdByAngle?(b=(e/Math.PI*180+c.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=
b):a.clientX=a.plotX};e.spline&&(d(e.spline.prototype,"getPointSpline",function(a,b,c,d){this.chart.polar?d?(a=this.getConnectors(b,d,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,d);return a}),e.areasplinerange&&(e.areasplinerange.prototype.getPointSpline=e.spline.prototype.getPointSpline));c(v,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=
a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var b=this.points,d=b.length;d--;)this.toXY(b[d]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&b[d].y<this.yAxis.min&&(b[d].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(c(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2,innerR:b[3]/
2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=h.noop}})))}},{order:2});d(F,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var g=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));
g&&b.pop();return d});var x=function(a,b){var c=this,d=this.chart,e=this.options.animation,g=this.group,f=this.markerGroup,k=this.xAxis.center,l=d.plotLeft,r=d.plotTop,n,p,q,t;if(d.polar)if(c.isRadialBar)b||(c.startAngleRad=y(c.translatedThreshold,c.xAxis.startAngleRad),h.seriesTypes.pie.prototype.animate.call(c,b));else{if(d.renderer.isSVG)if(e=w(e),c.is("column")){if(!b){var v=k[3]/2;c.points.forEach(function(a){n=a.graphic;q=(p=a.shapeArgs)&&p.r;t=p&&p.innerR;n&&p&&(n.attr({r:v,innerR:v}),n.animate({r:q,
innerR:t},c.options.animation))})}}else b?(a={translateX:k[0]+l,translateY:k[1]+r,scaleX:.001,scaleY:.001},g.attr(a),f&&f.attr(a)):(a={translateX:l,translateY:r,scaleX:1,scaleY:1},g.animate(a,e),f&&f.animate(a,e))}else a.call(this,b)};d(F,"animate",x);if(e.column){var p=e.arearange.prototype;e=e.column.prototype;e.polarArc=function(a,b,c,d){var e=this.xAxis.center,g=this.yAxis.len,f=e[3]/2;b=g-b+f;a=g-y(a,g)+f;this.yAxis.reversed&&(0>b&&(b=f),0>a&&(a=f));return{x:e[0],y:e[1],r:b,innerR:a,start:c,
end:d}};d(e,"animate",x);d(e,"translate",function(a){var b=this.options,c=b.stacking,d=this.chart,e=this.xAxis,f=this.yAxis,h=f.reversed,l=f.center,r=e.startAngleRad,p=e.endAngleRad-r;this.preventPostTranslate=!0;a.call(this);if(e.isRadial){a=this.points;e=a.length;var q=f.translate(f.min);var v=f.translate(f.max);b=b.threshold||0;if(d.inverted&&t(b)){var w=f.translate(b);k(w)&&(0>w?w=0:w>p&&(w=p),this.translatedThreshold=w+r)}for(;e--;){b=a[e];var x=b.barX;var y=b.x;var z=b.y;b.shapeType="arc";if(d.inverted){b.plotY=
f.translate(z);if(c&&f.stacking){if(z=f.stacking.stacks[(0>z?"-":"")+this.stackKey],this.visible&&z&&z[y]&&!b.isNull){var B=z[y].points[this.getStackIndicator(void 0,y,this.index).key];var E=f.translate(B[0]);B=f.translate(B[1]);k(E)&&(E=n.clamp(E,0,p))}}else E=w,B=b.plotY;E>B&&(B=[E,E=B][0]);if(!h)if(E<q)E=q;else if(B>v)B=v;else{if(B<q||E>v)E=B=0}else if(B>q)B=q;else if(E<v)E=v;else if(E>q||B<v)E=B=p;f.min>f.max&&(E=B=h?p:0);E+=r;B+=r;l&&(b.barX=x+=l[3]/2);y=Math.max(x,0);z=Math.max(x+b.pointWidth,
0);b.shapeArgs={x:l&&l[0],y:l&&l[1],r:z,innerR:y,start:E,end:B};b.opacity=E===B?0:void 0;b.plotY=(k(this.translatedThreshold)&&(E<this.translatedThreshold?E:B))-r}else E=x+r,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,E,E+b.pointWidth);this.toXY(b);d.inverted?(x=f.postTranslate(b.rectPlotY,x+b.pointWidth/2),b.tooltipPos=[x.x-d.plotLeft,x.y-d.plotTop]):b.tooltipPos=[b.plotX,b.plotY];l&&(b.ttBelow=b.plotY>l[1])}}});e.findAlignments=function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>
a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b};p&&(p.findAlignments=e.findAlignments);d(e,"alignDataLabel",function(a,b,c,d,e,f){var g=this.chart,h=y(d.inside,!!this.options.stacking);g.polar?(a=b.rectPlotX/Math.PI*180,g.inverted?(this.forceDL=g.isInsidePlot(b.plotX,Math.round(b.plotY),!1),h&&b.shapeArgs?(e=b.shapeArgs,e=this.yAxis.postTranslate((e.start+e.end)/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),e={x:e.x-g.plotLeft,
y:e.y-g.plotTop}):b.tooltipPos&&(e={x:b.tooltipPos[0],y:b.tooltipPos[1]}),d.align=y(d.align,"center"),d.verticalAlign=y(d.verticalAlign,"middle")):this.findAlignments&&(d=this.findAlignments(a,d)),F.alignDataLabel.call(this,b,c,d,e,f),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,d,e,f)})}d(a,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=
b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});q.prototype.clipCircle=function(a,b,c,d){var e=B(),f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=d?this.arc(a,b,c,d,0,2*Math.PI).add(f):this.circle(a,b,c).add(f);a.id=e;a.clipPath=f;return a};c(b,"getAxes",function(){this.pane||(this.pane=[]);z(this.options.pane).forEach(function(a){new f(a,
this)},this)});c(b,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});c(v,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});d(b.prototype,"get",function(a,b){return l(this.pane,function(a){return a.options.id===b})||a.call(this,b)})});z(d,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map